### ISSUE TITLE
Create a map from the recorded scan of the U.08 track

### ISSUE THREAD

**Issue by marian42** [Autonomous-Racing-PG/ros.package#180]
[Find the rosbag here](https://depot.tu-dortmund.de/pttww).  
[Second rosbag](http://depot.tu-dortmund.de/hy68d)

Try to create a map with gmapping or hectorslam.

Tutorials:
http://wiki.ros.org/hector_slam/Tutorials/MappingUsingLoggedData
http://wiki.ros.org/cn/slam_gmapping/Tutorials/MappingFromLoggedData

Note that our current rosbag does not have any transform/odometry data. Part of this task is finding out if  mapping is even possible in this case.

**Comment by Nils-Jung** [comment]
The rosbags are not available anymore and it's not really necessary anyway.
