### ISSUE TITLE
Function to get LIDAR range data for a certain degree is implemented at least twice

### ISSUE THREAD

**Issue by Dadie** [Autonomous-Racing-PG/ros.package#194]
The function 
```C++
float EmergencyStop::rangeAtDegree(const sensor_msgs::LaserScan::ConstPtr&, float)
``` 
in  `ros_ws/src/autonomous/src/emergency_stop.cpp` and the function 
```C++
float WallFollowing::getRangeAtDegree(const sensor_msgs::LaserScan::ConstPtr&, float)
```
in `ros_ws/src/autonomous/src/wall_following.cpp` implement both a function go get LIDAR range data for a certain degree. This should be refactored to make sure the range data for a certain degree is consistent between both classes.

**Comment by marian42** [comment]
After taking a closer look at the emergency stop code, I think after refactoring it, it will no longer need the `rangeAtDegree` function. Working on this now...
