### ISSUE TITLE
Add emergency stop to wall_following2

### ISSUE THREAD

**Issue by Nils-Jung** [Autonomous-Racing-PG/ros.package#232]

**Comment by marian42** [comment]
I think it would make sense to handle emergency stop in a similar way as the Dead Man's Switch currently works. We could have multiple publishers that send an emergency stop message and then stop regardless of the current autonomous controller. This could be done in the multiplexer or in the dms_controller.

**Comment by marian42** [comment]
For example, the Q value in Q learning is a predictor for how long it will take until the car crashes. The q_learning node could publish an emergency stop message once the Q value drops below a threshold.
