### ISSUE TITLE
Investigate performance in Gazebo

### ISSUE THREAD

**Issue by marian42** [Autonomous-Racing-PG/ros.package#308]
Recently, the real time factor in Gazebo dropped (from ~0.9 to ~0.5).

One way to find out would be to check out recent commits and see when the problem occured.

**Comment by Nils-Jung** [comment]
I am unable to reproduce this, my real time factor of ~0.65 has not changed for months. Could this be a problem unique to you?

**Comment by marian42** [comment]
0.65 seems low. I remember it being higher. If it was always like this, it's not a bug and can be closed.

**Comment by marian42** [comment]
It seems like performance did not get worse
