### ISSUE TITLE
Reconsider license choise

### ISSUE THREAD

**Issue by StefanJVA** [Autonomous-Racing-PG/ros.package#7]
We decided on unsing the MIT license for our project. However, in order to win a price money at the f1/10 events our code needs to be under the GPL license. 

- [x] everyone has to approve it

**Comment by Dadie** [comment]
We could simply dual license our code under MIT and GPLv3. This could in theory solve all our issues. Big projects like Rust do this, so it's not that uncommen. We might as well just tri license MIT/Apache/GPLv3 or quad license MIT/Apache/GPLv2/GPLv3 (as v2 and v3 of the GPL are AFAIK not compatible)
